version: '3'

services:
  hsdnode0:
    container_name: hsdnode0
    image: "falcon0125/hsdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-hsd.log}
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  hsdnode1:
    container_name: hsdnode1
    image: "falcon0125/hsdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-hsd.log}
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  hsdnode2:
    container_name: hsdnode2
    image: "falcon0125/hsdnode"
    environment:
      - ID=2
      - LOG=${LOG:-hsd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  hsdnode3:
    container_name: hsdnode3
    image: "falcon0125/hsdnode"
    environment:
      - ID=3
      - LOG=${LOG:-hsd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  hsclinode1:
    stdin_open: true
    tty: true
    container_name: hsclinode1
    image: "falcon0125/hsclinode"
    environment:
      - ID=4
      - LOG=${LOG:-hscli.log}
    ports:
      - "26665-26666:26656-26657"
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6

  hsclinode2:
    stdin_open: true
    tty: true
    container_name: hsclinode2
    image: "falcon0125/hsclinode"
    environment:
      - ID=5
      - LOG=${LOG:-hscli.log}
    ports:
      - "26667-26668:26656-26657"
    volumes:
      - ./build/testnet:/root:Z
      - ./build/bin:/usr/local/bin:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16